name: Deploy static site to S3 (website-presentation)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # für OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login in AWS via OIDC (keine Access Keys nötig)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::285513790190:role/Github
          aws-region: eu-central-1

      # Sync NUR Web-Dateien aus dem Repo-Root -> S3
      # (verhindert, dass .github/ oder README.md hochgeladen werden)
      - name: Upload web files to S3
        run: |
          aws s3 sync . s3://website-presentation --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "LICENSE" \
            --exclude "README.md" \
            --exclude ".gitignore" \
            --exclude ".DS_Store" \
            --exclude "*.yml" \
            --exclude "*.yaml" \
            --exclude "*.md" \
            --exclude "*.toml" \
            --exclude "*.json" \
            --exclude "*.lock" \
            --exclude "node_modules/*"

      # Wichtig: index.html ohne Cache ausliefern, damit Änderungen sofort sichtbar sind
      - name: Set cache headers for index.html
        run: |
          aws s3 cp index.html s3://website-presentation/index.html \
            --cache-control "no-store, must-revalidate" \
            --content-type "text/html; charset=utf-8" \
            --metadata-directive REPLACE
